version: '2'
volumes:
    resin-data:
services:
  fluentd:
    build: ./fluentd
    expose:
      - 24224
    volumes:
      - 'resin-data:/data'
  speedtest:
    build: ./speedtest
    depends_on:
      - fluentd
    environment:
      - TEST_INTERVAL_SECONDS=300
      - CONNECTION_ID
      - FLUENT_HOSTNAME=fluentd
      - FLUENT_PORT=24224
    links:
      - fluentd:fluentd
