version: '2'
volumes:
    resin-data:
services:
  helloworld:
    image: resin/raspberrypi3-python:slim
    volumes:
      - 'resin-data:/data'
    command: |
      /bin/bash -c "while true; do echo \"Sleeping\"; sleep 1; done"
