version: '2'
services:
  fluentd:
    build: ./fluentd
    expose:
      - 24224
    environment:
      - FLUENTD_OPT="-v"
  speedtest:
    build: ./speedtest
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: speedtest.telecolumbus
