version: '2'
volumes:
    resin-data:
services:
  helloworld:
    image: resin/raspberrypi3-python:slim
    volumes:
      - 'resin-data:/data'
    command: |
      while true; do
        date >> /data/helloworld.txt
        echo "Sleeping"
        sleep 1
      done
