version: '2'
volumes:
    resin-data:
services:
  fluentd:
    build: ./fluentd
    hostname: fluentd-service
    expose:
      - 24224
    volumes:
      - 'resin-data:/data'
  speedtest:
    build: ./speedtest
    depends_on:
      - fluentd
    environment:
      - TEST_INTERVAL_SECONDS=300
      - CONNECTION_ID=${RESIN_DEVICE_NAME_AT_INIT}
      - FLUENT_HOSTNAME="fluentd-service"
      - FLUENT_PORT=24224
    command: |
      /bin/bash -c "
        while true; do
          echo "Sleeping"
          sleep 10
        done
      "
